### ISSUE TITLE
Center the Todo or Powered by Kitura logo

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/TodoList-iOS#13] opened 2016-10-19 16:15 UTC

**Comment by jesspittman** [comment] 2016-10-20 17:22
This has been addressed in a recent commit. The splash screen screenshot still needs to be updated though.

This issue was caused by the image being centered itself, but the main content of the image was on the left. This made the image look slightly off center.

**Comment by rfdickerson** [comment] 2016-10-20 22:47
Yeah, let's see if we can have quick design help on this.

**Closed** 2016-10-21 22:00 UTC
Labels: enhancement
